
```{r global_options}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, messages=FALSE)
```

```{r packages}
# Load all of the packages
# Commented lines are packages that may need installation

library(readr)
#install.packages("devtools")
#library(devtools)
#install_github('arilamstein/choroplethrZip@v1.3.0')
library(choroplethrZip)
library(ggplot2)
library(stringr)
library(dplyr)
library(zipcode)
#install.packages("genderdata")
library(gender)
library(rvest)
library(lubridate)
library(gridExtra)
library(RColorBrewer)
library(ggthemes)
library(polycor)
#library(GGally)
library(memisc)

# could not find url or was changed
#download.file()

# note that loading and munging the data can be skipped, and tidy data sets
# can be sourced from the last chunk before the univariate plots section
```

```{r}
load("processed-data.Rdata")
```

```{r experimental_plots, eval=FALSE}
total_amt_dem_df <- df[(df$party == "democrat"), ] %>% group_by(zipcode) %>% summarise(total_amt = sum(amount))
quants <- quantile(total_amt_dem_df$total_amt, probs = c(0, .15, .3, .45, .55, .70, .85, 1))
mapdata.ohio.totals <- merge(mapdata.ohio, total_amt_dem_df,
                                by.x = 'region', by.y = 'zipcode',
                                all.x = TRUE) %>% arrange(order)

# ggvis
library(ggvis)
mapdata.ohio.totals %>%
  ggvis(~long, ~lat) %>% group_by(group) %>%
  layer_paths(fill =~cut(total_amt, breaks = quants, include.lowest = TRUE)) %>%
  scale_ordinal("fill", range=c("#fee5d9", "#fcbba1", "#fc9272", "#fb6a4a", "#ef3b2c", "#cb181d", "#99000d"))

# leaflet
library(leaflet)
leaflet_map <- mapdata.ohio.totals[1:400, ]
#split(leaflet_map, leaflet_map$group)
for(row in leaflet_map[1:20, ]) {
  print(row["group"])
}
library(rgdal) #maptools?
leaflet_map[149, ] <- rep(NA, ncol(leaflet_map))
leaflet() %>% addTiles() %>% addPolygons(data = leaflet_map, lng = ~long, lat = ~lat, color = ~pal(total_amt))

# ggmaps
library(ggmap)
qmap('ohio', zoom = 7, maptype = 'roadmap')
```
